name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get the tag string
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_ENV"
    - name: Build the Docker image
      env:
        VERSION: ${{ env.VERSION }}
      run: docker build . --file Dockerfile --tag ghcr.io/lyzardking/jupyter-prolog:$VERSION
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push images to kubernetes
      env:
        VERSION: ${{ env.VERSION }}
      run: |
        docker push ghcr.io/lyzardking/jupyter-prolog:$VERSION
        docker tag ghcr.io/lyzardking/jupyter-prolog:$VERSION ghcr.io/lyzardking/jupyter-prolog
        docker push ghcr.io/lyzardking/jupyter-prolog